---
- name: Install PHP 8.1 on Debian 12
  hosts: all
  become: true  # Allows tasks to run with elevated privileges

  tasks:
    - name: Ensure essential packages are installed
      apt:
        name:
          - lsb-release
          - ca-certificates
          - apt-transport-https
          - software-properties-common
          - gnupg2
        state: present
      # Update package lists before and after adding repository

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Get distribution codename
      shell: lsb_release -sc
      register: codename

    - name: Add SURY.ORG repository for PHP 8.1
      apt_repository:
        repo: 'deb https://packages.sury.org/php/ {{ codename.stdout }} main'
        state: present
      # Use ansible_distribution_release variable instead of shell commands

    - name: Import SURY.ORG GPG key
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present
      # Separate key management using apt_key module

    - name: Update package lists (again)
      apt:
        update_cache: yes

    - name: Install PHP 8.1 and required extensions
      apt:
        name:
          - php8.1-cli
          - php8.1-fpm  # Add other extensions as needed
        state: present

    - name: Verify PHP version
      command: php -v | head -n 1 | cut -d " " -f 2
      register: php_version
      changed_when: false

    - name: Display PHP version
      debug:
        msg: "PHP version is {{ php_version.stdout }}"
