---
- name: Install Java on slave1
  hosts: slave1
  become: true  # Allow tasks with root privileges

  tasks:
    - name: Update package lists
      apt: update_cache=yes

    - name: Install Java OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present
