---
- name: Install and configure Apache2
  hosts: slave1
  become: true

  tasks:
  - name: update cache
    apt: update_cache=yes

  - name: Install Apache2
    apt: name=apache2 state=present

  - name: Start and enable apache2 service
    service: name=apache2 state=started
